Fix trackjoint compile errors
Commit 518206d5 in the `trackjoint` repo refactored the
`ErrorCodeEnum`, changing symbol names.  This patch mirrors those
changes on this side.

    Errors     << moveit_simple_controller_manager:make [...]/logs/moveit_simple_controller_manager/build.make.000.log
    [...]/moveit/moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp: In member function ‘virtual bool moveit_simple_controller_manager::FollowJointTrajectoryControllerHandle::sendTrajectory(const RobotTrajectory&)’:
    [...]/moveit/moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp:151:69: error: ‘kNoError’ is not a member of ‘trackjoint::ErrorCodeEnum’
       trackjoint::ErrorCodeEnum error_code = trackjoint::ErrorCodeEnum::kNoError;
									 ^~~~~~~~
    [...]/moveit/moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp:170:48: error: ‘kErrorCodeMap’ is not a member of ‘trackjoint’
	 std::cout << "Error code: " << trackjoint::kErrorCodeMap.at(error_code)
						    ^~~~~~~~~~~~~
    [...]/moveit/moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp:170:48: note: suggested alternative: ‘ErrorCodeEnum’
	 std::cout << "Error code: " << trackjoint::kErrorCodeMap.at(error_code)
						    ^~~~~~~~~~~~~
						    ErrorCodeEnum
    [...]/moveit/moveit_plugins/moveit_simple_controller_manager/src/follow_joint_trajectory_controller_handle.cpp:174:50: error: ‘kNoError’ is not a member of ‘trackjoint::ErrorCodeEnum’
	 if (error_code != trackjoint::ErrorCodeEnum::kNoError)
						      ^~~~~~~~
    make[2]: *** [CMakeFiles/moveit_simple_controller_manager.dir/src/follow_joint_trajectory_controller_handle.cpp.o] Error 1
    make[1]: *** [CMakeFiles/moveit_simple_controller_manager.dir/all] Error 2
    make: *** [all] Error 2